### ISSUE TITLE
Render button is disabled

### ISSUE THREAD

**Issue by tin2tin** [samytichadou/Playblaster#1]
![image](https://user-images.githubusercontent.com/1322593/80541736-fa4d3c00-89ab-11ea-896d-b18c09c356a5.png)

Any ideas why?

(I wish I could see that gif in the wiki - but it's gone)

**Comment by samytichadou** [comment]
Hi a little bit late, sorry, didn't see this issue, sometimes if blender crashes while playblasting, there is a _is_working_ property which can stay on, and prevent the operator to work. You can just click debug in the top panel, and toggle this property off, it will allow you to playblast !
